map_type: costmap
transform_tolerance: 0.2 # Default 0.2, tol in [s] to wait for transform

obstacle_range: 10.0
max_obstacle_height: 2.0
min_obstacle_height: 0.0
raytrace_range: 10.0 # max range [m] to raytrace out obstacles
inscribed_radius: 0.35
circumscribed_radius: 0.4
inflation_radius: 0.55
cost_scaling_factor: 10.0
lethal_cost_threshold: 100
footprint: [[-0.13, 0.11], [0.13, 0.11], [0.13, -0.11], [-0.13, -0.11]]

observation_sources: hokuyo_laser_scan_sensor

hokuyo_laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true,  expected_update_rate: 0.2}



