explore_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 1.0
  publish_frequency: 0.0
  raytrace_range: 10.0
  obstacle_range: 10.0
  static_map: false
  rolling_window: true # example shows both at false?
  width: 60.0
  height: 60.0
  resolution: 0.2
  origin_x: -30.0
  origin_y: -30.0
  track_unknown_space: true
